### ISSUE TITLE
live stream process in mux using php

### ISSUE THREAD

**Issue by Ebtighaa** [muxinc/mux-php#16]
Dear Sir..

Hope you are doing well

am trying to use your live stream api, i previously contacted you on github (https://github.com/muxinc/mux-php/issues/15)..

it worked fine for me, thanks

now am asking about how to push live stream to mux..

meaning: i successfully opened my webcam in my browser (inside my web app), how to send this live stream to mux servers using RTMP Protocol, i found multiple apps as solutions for that in mux documentation , one desktop applications for live and one command line program for assets, but i need to do this programmatically in my code..

i hope i clearly explained my request..

Thanks in advanced..

**Comment by mmcc** [comment]
Hi there, streaming RTMP directly from the browser isn’t possible. I wrote a [blog post](https://mux.com/blog/the-state-of-going-live-from-a-browser/) on the options there.
