### ISSUE TITLE
File type not detected when url is indirect (no file type in Url)

### ISSUE THREAD

**Issue by azpery** [muxinc/mux-php#17]
Hi,

First thank you for your work. 

I'd like to know if there a way to pass the file type in the payload rather than in the url. 

_I explain:_
When I had a media with url : http://filemanager.robin-delaporte.fr/file_example_MP4_1920_18MG.**mp4** , the API detects that the file is a **MP4**. But when I send this url : http://filemanager.robin-delaporte.fr/?r=/download&path=L3Rlc3R0ZW5rL2ZpbGVfZXhhbXBsZV9NUDRfMTkyMF8xOE1HLm1wNA%3D%3D the API returns "The input file was not a valid video or audio file."

**Comment by GeneticGenesis** [comment]
Hey @azpery,

You can use the Mux Direct Uploads feature to push a file to Mux from a device: https://docs.mux.com/docs/direct-upload

You can create a direct upload using this SDK: https://github.com/muxinc/mux-php/blob/master/examples/video/exercise-uploads.php

Thanks!

**Comment by azpery** [comment]
Hello @GeneticGenesis ,

Thanks for your answer. Actually we absolutely need to upload the media through the url feature.

**Comment by GeneticGenesis** [comment]
Sorry @azpery, I misunderstood the question here.

Since this isn't related to the PHP SDK, please can you drop us a message on help AT mux.com and we'll take a look.

Thanks.

**Comment by azpery** [comment]
No problem, I send you a message at mux.com :) 

Thanks
