### ISSUE TITLE
Guzzle version

### ISSUE THREAD

**Issue by j-dexx** [muxinc/mux-php#20]
Hi,

Is there a plan to update to support the latest version of guzzle?  

https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

A quick skim of the mux codebase suggests that there shouldn't really be any issues. 

Thanks.

**Comment by GeneticGenesis** [comment]
Hey @j-dexx, sure, we'll take a look at this for the next release.

Thanks!

**Comment by j-dexx** [comment]
Thanks @GeneticGenesis

**Comment by LukeAbell** [comment]
@GeneticGenesis Any ETA on this? Laravel 8 now requires Guzzle 7 and the mux package guzzle dependency is blocking our upgrade

**Comment by darcyrailip** [comment]
@GeneticGenesis Chiming in here as well, would be great to upgrade!

**Comment by jbardnz** [comment]
Also really keen on this as well.

**Comment by j-dexx** [comment]
> 
> 
> @GeneticGenesis Any ETA on this? Laravel 8 now requires Guzzle 7 and the mux package guzzle dependency is blocking our upgrade

@LukeAbell 

Laravel 8 Supports guzzle 6.5.5 doesn't it?

**Comment by GeneticGenesis** [comment]
Hey everyone, thanks for your feedback here, I've been unavailable for a few weeks, I'm going to try to get this in over the next week or two.

Thanks.

**Comment by GeneticGenesis** [comment]
Hey everyone, I've tested against latest Guzzle, and all looks good, we'll be bumping to Guzzle ^7:

https://github.com/muxinc/mux-php/pull/21/files

I've merged a PR into our internal templates, and a public version will go live in the next week or so.

Thanks.

**Comment by GeneticGenesis** [comment]
This is released in 0.6.0 which is available now. Thanks for your patience everyone.
