### ISSUE TITLE
Webhook signature verification

### ISSUE THREAD

**Issue by mikemike** [muxinc/mux-php#25]
Other Mux SDKs (node and Elixir) include a way to verify signatures within webhooks, but the PHP one does not.  There are instructions on how to do this manually, but given that handling webhooks are so pivotal to a Mux integration, and the importance of security, it seems sensible to include a method to do this as a priority.

Verifying the signature seems straightforward until the comparison based around the timestamp.  It looks like the timestamp sent from Mux cannot be relied upon as it might differ by a few seconds to the server time, which would make the signature mismatch.  Looking at the nodejs method of verifying there's a function available called `crypto.timingSafeEqual`, which allows comparisons on this, but I'm unsure of a PHP equivalent.  Code for this here: https://github.com/muxinc/mux-node-sdk/blob/master/src/webhooks/resources/verify_header.js#L22

It would be great if we could get a webhook class added to the PHP library to make verifying webhook signatures as easy as the rest of the API is to work with.

**Comment by GeneticGenesis** [comment]
Hey @mikemike, thanks for raising this. 

The PHP, Python, Ruby and Go SDKs are generated from our OpenAPI definitions, which doesn't cover Webhook signatures today, it's all custom code we'd have to inject into the generation process.

This is on our backlog to look at along with JWT signing for code generated SDKs.

I don't believe `crypto.timingSafeEqual` is actually what's allowing for the offset based on the documentation here: https://nodejs.org/api/crypto.html#crypto_crypto_timingsafeequal_a_b - it's just a secure way of comparing two values.

The code you should replicate in PHP to handle the timing offset is here (tolerance is set to 5 mins at the top of the file): https://github.com/muxinc/mux-node-sdk/blob/master/src/webhooks/resources/verify_header.js#L103-L109

Thanks!

**Comment by mikemike** [comment]
Ah yeah, looks like I've mis-read it.

I've actually managed to write a working method without much issue at all.  Have a feeling others might struggle though, so I'm more than happy for you to add this to your docs if you feel that appropriate.  This is in Laravel, so `Str` and `$request` are both part of the framework but pretty obvious what they both are and are doing.

```
    /**
     * Verify the signature
     * 
     * @param Request $request
     * @return boolean
     */
    protected function verifySignature(Request $request)
    {
        // Get the signature from the request header
        $muxSig = $request->header('Mux-Signature');

        if(empty($muxSig)) {
            return false;
        }

        // Split the signature based on ','.
        // Format is 't=[timestamp],v1=[hash]'
        $muxSigArray = explode(',', $muxSig);

        if(empty($muxSigArray) || empty($muxSigArray[0]) || empty($muxSigArray[1])) {
            return false;
        }

        // Strip the first occurence of 't=' and 'v1=' from both strings
        $muxTimestamp = Str::replaceFirst('t=', '', $muxSigArray[0]);
        $muxHash = Str::replaceFirst('v1=', '', $muxSigArray[1]);

        // Create a payload of the timestamp from the Mux signature and the request body with a '.' in-between
        $payload = $muxTimestamp . "." . $request->getContent();

        // Build a HMAC hash using SHA256 algo, using our webhook secret
        $ourSignature = hash_hmac('sha256', $payload, config('mux.webhook_secret'));

        // `hash_equals` performs a timing-safe crypto comparison
        return hash_equals($ourSignature, $muxHash);
    }
```

**Comment by GeneticGenesis** [comment]
Hey @mikemike, thanks for sending this over, we're adding a version of this to our docs.

Thanks again!
