### ISSUE TITLE
Params not being passed with JWT

### ISSUE THREAD

**Issue by mikemike** [muxinc/mux-php#26]
I'm trying to pass some parameters via my JWT to the API.  In this case I want to edit the start time on a gif, but there are other things I'm attempting too.

As per the docs I'm calling:
`JWT::encode($payload, base64_decode($keySecret), 'RS256')`

In this instance below is my `$payload` (I've redacted the sub and kid):
```
array:5 [
  "sub" => "************"
  "aud" => "g"
  "exp" => 1613156632
  "kid" => "**********"
  "params" => array:1 [
    "start" => 30
  ]
]
```

This gives me a token, which is valid, and appending it to my `animated.gif` URL does give me a gif, however the `start` param is totally ignored.  I've tried various values here including `fps` and `end`, as well as `width` and `height` when generating thumbnails.  However, nothing I do affects the output, it's always a 15fps gif starting from 0s.

What am I missing?

**Comment by dylanjha** [comment]
@mikemike can you try this for the `$payload`?

```
array:5 [
  "sub" => "************"
  "aud" => "g"
  "exp" => 1613156632
  "kid" => "**********"
   "start" => 30
]
```

**Comment by mikemike** [comment]
Perfect, that works.  Thanks.

Might be worth updating the docs to include this.  It's slightly different under the node JWT implementation - understandably as it uses a different library.

Cheers
