### ISSUE TITLE
Add/update listDimensionValues() filter criteria/format for clarity

### ISSUE THREAD

**Issue by aminamos** [muxinc/mux-php#35]
Ensure that array methods fit expectations for - https://github.com/muxinc/mux-php/blob/master/docs/Api/DimensionsApi.md

Working example: `$dimensionValues = $dimensionsApi->listDimensionValues("browser", ["timeframe" => ["30:days"], 'filters' => ['region:Washington']]);`

This example isn't listed in the README or API example

**Comment by philcluff** [comment]
Merged! Thanks!
