### ISSUE TITLE
Conflicting Guzzle versions

### ISSUE THREAD

**Issue by rcapile** [muxinc/mux-php#37]
On version `0.6` it was bumped to Guzzle version 7. But on `1.0.0-rc` it's using 6.2 again.

I noticed that on branch `ed/sdk-ng` was reverted and there's also a PR still opened for the same branch without any mention of this downgrade. Was this downgrade intentional or slipped?

**Comment by eropple** [comment]
Hey there! Version downgrade was a slip-up as we pulled in some new OpenAPI templates. We'll make sure 1.0.0 (which should go out today) has that restored.

**Comment by philcluff** [comment]
Hi @rcapile, this should be resolved in > 1.0, please pull the latest package and let us know if this is still a problem.

Thanks.
