### ISSUE TITLE
createLiveStream Not accept param reconnect_window

### ISSUE THREAD

**Issue by PeanutSquareLLP** [muxinc/mux-php#4]

**Comment by GeneticGenesis** [comment]
Hi @PeanutSquareLLP, thanks for letting us know, I'll take a look at this today.

**Comment by GeneticGenesis** [comment]
Hi @PeanutSquareLLP, I've released 0.0.2 to [packagist](https://packagist.org/packages/muxinc/mux-php) with a fix for this issue. 

Thanks for letting us know, please reach out if you have any other issues.

Thanks!

**Comment by PeanutSquareLLP** [comment]
Thanks it works
