### ISSUE TITLE
Possible typo in constant name: PlaybackPolicy::_PUBLIC

### ISSUE THREAD

**Issue by denismosolov** [muxinc/mux-php#42]
I wonder if `PlaybackPolicy::_PUBLIC` should be `PlaybackPolicy::PUBLIC`, similar to `PlaybackPolicy::SIGNED`.

**Comment by philcluff** [comment]
Hey @denismosolov, this is deliberate, `public` is a reserved word, and is case insensitive, so we can't use just `PUBLIC` for this. 

Thanks.
