### ISSUE TITLE
Generative subtitles not creating track when using createDirectUpload

### ISSUE THREAD

**Issue by a-am** [muxinc/mux-php#78]
When using `createDirectUpload` generative_subtitles array is removed from upload object.  

```
$subtitles = new MuxPhp\Models\AssetGeneratedSubtitleSettings(["language_code" => "en", "name" => "English CC"]);
$inputSettings = new MuxPhp\Models\InputSettings(["generated_subtitles" => $subtitles]);
$createAssetRequest = new MuxPhp\Models\CreateAssetRequest(["input" => $inputSettings, "playback_policy" => [$policy], "max_resolution_tier" => $maxResolutionTier, "passthrough" => $passthrough]);
$createUploadRequest = new MuxPhp\Models\CreateUploadRequest(["timeout" => 3600, "new_asset_settings" => $createAssetRequest, "cors_origin" => UrlHelper::siteUrl()]);
        
$upload = $apiInstance->createDirectUpload($createUploadRequest);
```

If you dump the `$upload` the generative subtitle settings are not apart of the object.  When the upload completes and the asset is created the subtitles are not auto generating. The generative subtitle settings are present in the `$createUploadRequest` object at the time of assigning to `createDirectUpload`.
We are using a secure playback policy.  The videos successfully uploads and is playable however the auto generated track is not present.

PHP 8.2
mux-php 3.12.0

**Comment by dylanjha** [comment]
Hi @a-am thanks for opening. This was supposed to be added [in 3.12.0 release](https://github.com/muxinc/mux-php/releases/tag/3.12.0), let me followup on that release and see what's up

**Comment by philcluff** [comment]
Hey @a-am, just to confirm that generated captions are supported fully in 3.12.1. 3.12.0 does contain a bug which would have made the asset response invalid, even with the right API call, so please do upgrade to 3.12.1.

I added an [example use of generated vod captions with direct uploads here](https://github.com/muxinc/mux-php/blob/master/examples/video/exercise-uploads.php#L19-L22), there's a small bug in your invocation right now, you need to pass an _array_ to `input`, so just change it to `"input" => [$inputSettings]`, and it should work.

Let me know if you continue to run into problems here.

Thanks!
